app_contabilidad_inversiones/urls.py
from django.urls import path
from . import views # el . significa directorio actual

app_name = "app_contabilidad_inversiones"
urlpatterns = [
    path("", views.index, name="index"),
    path("resumen", views.resumen_inversiones, name="resumen_inversiones"),
    path("nueva_transaccion", views.ingresar_transaccion, name="ingresar_transaccion"),
    path("transacciones", views.ver_transacciones, name="ver_transacciones"),
    path("<int:transaccion_id>",views.ver_transaccion_individual, name="ver_transaccion_individual"),
    path("cotizaciones",views.ver_cotizaciones_actuales, name="ver_cotizaciones_actuales")
]

backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.conf.urls import url
# from rest_framework import routers
from self_index_app import views

# router = routers.DefaultRouter()
# router.register(r'investors', views.InvestorView, 'investor')
# router.register(r'transactions', views.TransactionView, 'transaction')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/investors/', views.investors_list),
    path('api/transactions/', views.add_transaction)
]

contabilidad_inversiones/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app_contabilidad_inversiones/', include("app_contabilidad_inversiones.urls")),
]

app_contabilidad_inversiones/models.py
from django.db import models

# Create your models here.
class Plataformas_inversion(models.Model):
    nombre_plataforma = models.CharField(max_length=12)

    def __str__(self):
        return f"Nombre de la plataforma: {self.nombre_plataforma}"

class Transacciones(models.Model): # Cada clase de Python es una tabla de SQL
    fecha = models.DateField()
    nombre = models.CharField(max_length=250)
    simbolo = models.CharField(max_length=4,null=True,blank=True,default=None)
    bolsa = models.CharField(max_length=4,null=True,blank=True,default=None)
    plataforma = models.ForeignKey(Plataformas_inversion,on_delete=models.CASCADE, related_name="plataformas")
    moneda = models.CharField(max_length=3)
    precio = models.DecimalField(decimal_places=2,max_digits=6)

    def __str__(self):
        return f"{self.nombre}({self.simbolo}): con un precio de {self.precio} {self.moneda} en la fecha {self.fecha}"

app_contabilidad_inversiones/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django import forms
from .models import Transacciones, Plataformas_inversion
from django.db.models import Max,Min
from . import funciones_python as fj
import pandas as pd

# Create your views here.
posibles_monedas = (
                        ('Original','Original'),
                        ('EUR','EUR'),
                        ('USD','USD'),
                    )

#################################### CLASES ####################################
class NewTransactionForm(forms.Form):
    date = forms.DateField(label=False,#widget=forms.DateInput(format="%d/%m/%Y"),
                            widget=forms.DateInput(attrs={'placeholder':'Fecha: dd/mm/yyyy'}),
                            input_formats=("%d/%m/%Y",))
    activo = forms.CharField(label=False,
                                widget=forms.TextInput(attrs={'placeholder':"Nombre del activo"}))
    plataforma = forms.ChoiceField(label=False,
                                    choices=(
                                        ('DE GIRO','DE GIRO'),
                                        ('MINTOS','MINTOS'),
                                        ('AXA','AXA')
                                        ))
    moneda = forms.ChoiceField(label=False,
                                    choices=posibles_monedas[1:])
    simbolo = forms.CharField(label=False, required=False,
                                widget=forms.TextInput(attrs={'placeholder':"Símbolo"}))
    bolsa = forms.CharField(label=False, required=False,
                                widget=forms.TextInput(attrs={'placeholder':"Bolsa (Yahoo Finance)"}))

    precio_transaccion = forms.DecimalField(label=False,decimal_places=2,min_value=0,
                                            widget=forms.TextInput(attrs={'placeholder':"Precio"}))

class EliminarTransactionForm(forms.Form):
    id_transaccion_eliminar = forms.IntegerField(
                        min_value=int(Transacciones.objects.values('id').aggregate(Min('id'))['id__min']),
                        max_value=int(Transacciones.objects.values('id').aggregate(Max('id'))['id__max']))

class Elegir_Moneda_a_mostrar(forms.Form):
    moneda_mostrar = forms.ChoiceField(label=False,
                                    choices=posibles_monedas)
class Elegir_Moneda_a_mostrar_dos_opciones(forms.Form):
    moneda_mostrar = forms.ChoiceField(label=False,
                                    choices=posibles_monedas[1:])
#################################### CLASES ####################################

#################################### VISTAS ####################################
def index(request):
    return render(request, "app_contabilidad_inversiones/index.html")

#precio,moneda = fj.conectarse_yahoo_finance(symbol='VOO',bolsa='AS')
#return render(request, "",{
#    "precio":precio,
#    "moneda":moneda
#})

def resumen_inversiones(request):
    if request.method == "POST":
        form = Elegir_Moneda_a_mostrar_dos_opciones(request.POST)
        moneda_mostrar = [request.POST.get("moneda_mostrar")][0]    
    else:
        moneda_mostrar = 'EUR'
        form = Elegir_Moneda_a_mostrar_dos_opciones()
    numero_transacciones = len(Transacciones.objects.all())
    numero_plataformas = len(Plataformas_inversion.objects.all())
    fechas,conteo_por_fecha = fj.obtener_fecha_numero_transacciones()
    plataformas,transacciones,dinero_por_plataforma = fj.obtener_resumen_por_plataforma(moneda_mostrar)
    return render(request, "app_contabilidad_inversiones/resumen.html",{
        "form":form,
        "numero_transacciones":numero_transacciones,
        "numero_plataformas":numero_plataformas,
        "transacciones":transacciones,
        "plataformas":plataformas,
        "fechas":fechas,
        "conteo_por_fecha":conteo_por_fecha,
        "dinero_por_plataforma":dinero_por_plataforma,
        "moneda_mostrar":moneda_mostrar
    })

def ingresar_transaccion(request):
    if request.method == "POST": # Si pulsamos el boton de enviar
        form = NewTransactionForm(request.POST) # Cogemos lo que estaba en el formulario que hemos enviado
        if form.is_valid(): # Si los datos del formulario son validos, los guardamos en variables y vamos a la url indicada
            fecha_transaccion = form.cleaned_data["date"]
            nombre_activo = form.cleaned_data["activo"].upper()
            plataforma = Plataformas_inversion.objects.get(nombre_plataforma=form.cleaned_data["plataforma"])
            moneda = form.cleaned_data["moneda"]
            precio_transaccion = form.cleaned_data["precio_transaccion"]
            simbolo = form.cleaned_data["simbolo"]
            bolsa = form.cleaned_data["bolsa"]

            nueva_transaccion = Transacciones(fecha=fecha_transaccion,nombre=nombre_activo,simbolo=simbolo,bolsa=bolsa,plataforma=plataforma,moneda=moneda,precio=precio_transaccion)
            nueva_transaccion.save()

            return HttpResponseRedirect(reverse("app_contabilidad_inversiones:index"))
        else: return render(request, "app_contabilidad_inversiones/ingresar_transaccion.html",{
            "form": form
            }) # Si los datos del formulario no son validos, devolvemos a la misma pagina, con los mismos datos para que los cambien

    return render(request, "app_contabilidad_inversiones/ingresar_transaccion.html",{
        "form":NewTransactionForm() # Si no hacemos POST, solo queremos que nos muestre la pagina con el formulario vacio
    })

def ver_transacciones(request):
    if request.method == "POST":
        form = Elegir_Moneda_a_mostrar(request.POST)
        moneda_mostrar = [request.POST.get("moneda_mostrar")][0]
        diccionario = {}
        ts = Transacciones.objects.all().order_by("fecha")
        currency_exchange = fj.conectarse_api_currency_exchange()
        for i in range(len(ts)):
            precio_convertido,moneda_convertida = fj.convertir_precio_moneda(moneda_mostrar,ts[i].moneda,ts[i].precio,currency_exchange)
            diccionario[ts[i].id] = {
                                        "fecha":ts[i].fecha,
                                        "nombre":ts[i].nombre,
                                        "simbolo":'' if pd.isnull(ts[i].simbolo) else ts[i].simbolo,
                                        "bolsa": '' if pd.isnull(ts[i].bolsa) else ts[i].bolsa,
                                        "precio":precio_convertido,
                                        "moneda":moneda_convertida,
                                        "plafatorma":ts[i].plataforma.nombre_plataforma,
                                    }
        return render(request, "app_contabilidad_inversiones/transacciones.html",{
            "transacciones":Transacciones.objects.all().order_by("fecha"),
            "diccionario_transacciones":diccionario,
            "form":form,
        })
    else:
        return render(request, "app_contabilidad_inversiones/transacciones.html",{
            "transacciones":Transacciones.objects.all().order_by("fecha"),
            "form":Elegir_Moneda_a_mostrar()
        })

def ver_transaccion_individual(request,transaccion_id):
    if request.method == "POST":
        Transacciones.objects.get(pk=int(transaccion_id)).delete()
        return HttpResponseRedirect(reverse("app_contabilidad_inversiones:ver_transacciones"))
    transaccion = Transacciones.objects.get(pk=transaccion_id)
    return render(request, "app_contabilidad_inversiones/transaccion_individual.html",{
                "transaccion":transaccion
    })

def ver_cotizaciones_actuales(request):
    if request.method == "POST":
        form = Elegir_Moneda_a_mostrar_dos_opciones(request.POST)
        moneda_mostrar = [request.POST.get("moneda_mostrar")][0]    
    else:
        moneda_mostrar = 'EUR'
        form = Elegir_Moneda_a_mostrar_dos_opciones()
    diccionario_precio_actual_stocks = fj.obtener_precio_actual_transacciones(moneda_mostrar)
    return render(request, "app_contabilidad_inversiones/ver_cotizaciones_actuales.html",{
        "form":form,
        "diccionario_precio_actual_stocks":diccionario_precio_actual_stocks
    })
#################################### VISTAS ####################################

app_contabilidad_inversiones/templates/app_contabilidad_inversiones/index.html
{% extends "app_contabilidad_inversiones/layout.html" %}

{% block body %}
    <h1 class="titulo">Bienvenido a su contabiliad de inversiones</h1>

    <form action="{% url 'app_contabilidad_inversiones:resumen_inversiones' %}" class="menu">
        <input type="submit" value="Ver resumen de inversiones" />
    </form>

    <!--Crear resumen transacciones (numero de transacciones, dinero invertido,...)-->
    <form action="{% url 'app_contabilidad_inversiones:ingresar_transaccion' %}" class="menu">
        <input type="submit" value="Ingresar nueva transacción" />
    </form>
    
    <!--Crear boton para linkear con ingresar nueva transaccion-->
    <form action="{% url 'app_contabilidad_inversiones:ver_transacciones' %}" class="menu">
        <input type="submit" value="Ver todas las transacciones" />
    </form>

    <!--Crear boton para linkear con ver cotizaciones actuales-->
    <form action="{% url 'app_contabilidad_inversiones:ver_cotizaciones_actuales' %}" class="menu">
        <input type="submit" value="Ver cotizaciones actuales" />
    </form>

{% endblock %}

app_contabilidad_inversiones/templates/app_contabilidad_inversiones/ingresar_transaccion.html
{% extends "app_contabilidad_inversiones/layout.html" %}

{% block body %}
    <h1 class="titulo">Ingresar nueva transacción</h1>
    <!--
    <form action="{% url 'app_contabilidad_inversiones:ingresar_transaccion' %}" method="POST">
        {% csrf_token %}
        <input type="date" placeholder="Fecha de la transacción" name="fecha_transaccion">
        <input type="text" placeholder="Nombre del activo" name="nombre_activo">
        <input list="plataformas_inversion" placeholder="Plataforma" name="plataforma_inversion">
            <datalist id="plataformas_inversion">
                <option value="MINTOS"></option>
                <option value="AXA"></option>
                <option value="DE GIRO"></option>
            </datalist>        
        <input type="number" step="0.01" placeholder="Precio (€)" name="precio_transaccion">
        <input type="submit" class="espacio_superior" name="envio_nueva_transaccion">
    </form>
    -->
    <form action="{% url 'app_contabilidad_inversiones:ingresar_transaccion' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>

    <div class="menu">
        <a href="{% url 'app_contabilidad_inversiones:index' %}">Volver a la página inicial</a>
    </div>

{% endblock %}

app_contabilidad_inversiones/templates/app_contabilidad_inversiones/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Contabiliad inversiones</title>
        <!-- Mis CSS -->
        <link href="{% static 'app_contabilidad_inversiones/styles.css' %}" rel="stylesheet">
        <!-- Mis CSS -->
        <!-- JavaScript con Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" 
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" 
        crossorigin="anonymous"></script>
        <!-- JavaScript con Popper -->
        <!-- Bootstrap -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" 
        rel="stylesheet" 
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" 
        crossorigin="anonymous">
        <!-- Bootstrap -->
        <!-- Charts js -->
        <script src="https://cdn.jsdelivr.net/npm/chart.js@3.2.1/dist/chart.min.js"></script>
        <!-- Charts js -->
        <!-- Mis funciones de JavaScript -->
        <script src="{% static 'app_contabilidad_inversiones/funciones_javascript.js' %}" type="text/javascript"></script>
        <!-- Mis funciones de JavaScript -->
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

app_contabilidad_inversiones/templates/app_contabilidad_inversiones/resumen.html
{% extends "app_contabilidad_inversiones/layout.html" %}
{% load static %}

{% block body %}
<h1 class="titulo">Resumen inversiones</h1>
<div>
    TOTAL de transacciones: {{ numero_transacciones }}
    <br>
    TOTAL de plataformas: {{ numero_plataformas }}
</div>

<div>
    <form action="{% url 'app_contabilidad_inversiones:resumen_inversiones' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Convertir">
    </form>
</div>
<!--Grafico combinado de transacciones y dinero por plataforma-->
<div class="chart-container" style="position: relative; height:300px; width:600px">
    <canvas id="mezcla"  height="300px" width="600px"></canvas>
</div>
<script>
show_mixed_charts(
    id_canvas = 'mezcla',
    titulo = '',
    labels_chart= ("{{ plataformas|safeseq|join:','}}").split(","),
    chart_type1='bar',
    label_chart1='número de transacciones',
    data1=("{{ transacciones|safeseq|join:',' }}").split(","),
    chart_type2='line',
    label_chart2=`Dinero ({{ moneda_mostrar }})`,
    data2=("{{ dinero_por_plataforma|safeseq|join:',' }}").split(",")
    )
</script>
<!--Grafico combinado de transacciones y dinero por plataforma-->

<!--Grafico de transacciones por fecha-->
<div class="chart-container" style="position: relative; height:200px; width:300px">
    <canvas id="transacciones_en_tiempo" width="10px"></canvas>
</div>
<script>
    show_chart(
        chart_type='line',
        id_canvas="transacciones_en_tiempo",
        titulo="Número de transacciones por fecha",
        labels_chart=("{{ fechas|safeseq|join:',' }}").split(','),
        label_chart='transacciones',
        data=("{{ conteo_por_fecha|safeseq|join:',' }}").split(",")
        )
</script>
<!--Grafico de transacciones por fecha-->

<div class="menu">
    <a href="{% url 'app_contabilidad_inversiones:index' %}">Volver a la página inicial</a>
</div>

{% endblock %}

app_contabilidad_inversiones/templates/app_contabilidad_inversiones/transaccion_individual.html
{% extends "app_contabilidad_inversiones/layout.html" %}

{% block body %}

    <div>
        ID de la transacción: {{ transaccion.id }}
        <br>
        Nombre de la transacción: {{ transaccion.nombre }}
        <br>
        Precio de la transacción: {{ transaccion.precio }} {{transaccion.moneda}}
        <br>
        Fecha de la transacción: {{ transaccion.fecha }}
    </div>
    <div class="llamativo_danger">
        ¿Desea eliminar esta transaccion?
    </div>
    <div>
        <form action="{% url 'app_contabilidad_inversiones:ver_transaccion_individual' transaccion.id %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="Eliminar">
        </form>
    </div>

    <div  class="menu">
        <a href="{% url 'app_contabilidad_inversiones:ver_transacciones' %}">Volver a todas las transacciones</a>
    </div>
{% endblock %}

app_contabilidad_inversiones/templates/app_contabilidad_inversiones/transacciones.html
{% extends "app_contabilidad_inversiones/layout.html" %}

{% block body %}
    <h1 class="titulo">Transacciones almacenadas</h1>
    <div>
        <form action="{% url 'app_contabilidad_inversiones:ver_transacciones' %}" method="POST">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Convertir">
        </form>
    </div>
    
    <div class="tabla">
        <table>
            <thead>
                <tr>
                    <th>FECHA</th>
                    <th>NOMBRE ACTIVO</th>
                    <th>SÍMBOLO</th>
                    <th>BOLSA</th>
                    <th>PRECIO</th>
                    <th>MONEDA</th>
                    <th>PLATAFORMA</th>
                </tr>
            </thead>
             {% if not diccionario_transacciones %}
                <tbody>
                    {% for trans in transacciones %}
                        <tr>
                            <td> {{trans.fecha}} </td>
                            <!-- <td>{{trans.nombre}}</td> -->
                            <td><a href="{% url 'app_contabilidad_inversiones:ver_transaccion_individual' trans.id %}">{{trans.nombre}}</a></td>
                            <td>
                                {% if trans.simbolo == None %}
                                    
                                {% else %}
                                    {{ trans.simbolo }}
                                {% endif %}
                            </td>
                            <td>
                                {% if trans.bolsa == None %}
                                    
                                {% else %}
                                    {{ trans.bolsa }}
                                {% endif %}
                            </td>
                            <td> {{trans.precio}} </td>
                            <td> {{ trans.moneda }} </td>
                            <td> {{trans.plataforma.nombre_plataforma}} </td>
                        </tr>
                    {% endfor %}
                </tbody>
            {% else %}
                <tbody>
                    {% for key,valor in diccionario_transacciones.items %}
                        <tr>
                            {% for key2,valor2 in valor.items %}
                                {% if key2 == "nombre" %}
                                    <td><a href="{% url 'app_contabilidad_inversiones:ver_transaccion_individual' key %}">{{valor2}}</a></td>
                                {% else %}
                                    <td>{{ valor2 }}</td>
                                {% endif %}     
                            {% endfor %}
                        </tr>
                    {% endfor %}
                </tbody>
            {% endif %}
        </table>
    </div>

    <div class="menu">
        <a href="{% url 'app_contabilidad_inversiones:index' %}">Volver a la página inicial</a>
    </div>
{% endblock %}

app_contabilidad_inversiones/templates/app_contabilidad_inversiones/ver_cotizaciones_actuales.html
{% extends "app_contabilidad_inversiones/layout.html" %}

{% block body %}
<h1 class="titulo">Cotizaciones actuales</h1>

<div>
    <form action="{% url 'app_contabilidad_inversiones:ver_cotizaciones_actuales' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Convertir">
    </form>
</div>


<div class="tabla">
    <table>
        <thead>
            <tr>
                <th>SÍMBOLO</th>
                <th>NOMBRE ACTIVO</th>
                <th>BOLSA</th>
                <th>PRECIO</th>
                <th>MONEDA</th>
            </tr>
        </thead>
            <tbody>
                {% for key,valor in diccionario_precio_actual_stocks.items %}
                    <tr>
                        <td>{{ key }}</td>
                        {% for key2,valor2 in valor.items %}
                            <td>{{ valor2 }}</td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
    </table>
</div>


<div class="menu">
    <a href="{% url 'app_contabilidad_inversiones:index' %}">Volver a la página inicial</a>
</div>

{% endblock %}